package com.rdm.uds.pautas.model

enum class OperacaoLogin {
    OK,
    EMAIL_INVALIDO,
    NOME_INVALIDO,
    SENHA_INVALIDA,
    REPETICAO_SENHA_DIFERENTE,
    USUARIO_NAO_AUTENTICADO,
    SENHA_FORMATO_INVALIDO,
    EMAIL_FORMATO_INVALIDO,
    USUARIO_INVALIDO,
    ERRO_CADASTRAR_USUARIO
}